@Library('olcne-pipeline')
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/.*', feature: 'feature/.*'),
        customStages: [container: [enabled: false]],
        platforms: ['ol8'],
  	ol8ModulesToEnable: ['go-toolset:ol8addon'],
)

